gpioEnabled: false

logging:
  level: INFO
  loggers:
    brewcontrol: DEBUG
  appenders:
    - type: console
      logFormat: "%-6level [%d{HH:mm:ss.SSS}] [%t] %logger{5} - %X{code} %msg %n"

database:
  driverClass: org.sqlite.JDBC
  url: jdbc:sqlite:./data.sqlite

server:
  rootPath: /api/